"""verify_phase8

Revision ID: 666ebb8f1779
Revises: 021303ba3ec2
Create Date: 2026-07-22 18:17:18.858093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '666ebb8f1779'
down_revision: Union[str, None] = '021303ba3ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_strategies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('skill_gap_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refresh_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_strategy_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('completed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('goal_completion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('milestone_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['career_strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_strategy_progress')
    op.drop_table('career_strategies')
    # ### end Alembic commands ###
