"""add career_intelligence_memory and snapshot index

Revision ID: b6d101cb675e
Revises: phase6_career_intelligence
Create Date: 2026-07-22 11:34:46.685240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6d101cb675e'
down_revision: Union[str, None] = 'phase6_career_intelligence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_intelligence_memories', sa.Column('memory_type', sa.String(), nullable=True))
    op.alter_column('career_intelligence_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('career_intelligence_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_career_intelligence_memories_conversation_id'), 'career_intelligence_memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_career_intelligence_memories_user_id'), 'career_intelligence_memories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'career_intelligence_memories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'career_intelligence_memories', type_='foreignkey')
    op.drop_index(op.f('ix_career_intelligence_memories_user_id'), table_name='career_intelligence_memories')
    op.drop_index(op.f('ix_career_intelligence_memories_conversation_id'), table_name='career_intelligence_memories')
    op.alter_column('career_intelligence_memories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('career_intelligence_memories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('career_intelligence_memories', 'memory_type')
    # ### end Alembic commands ###
