"""add career twin snapshot fields

Revision ID: bdec1b1fd5cb
Revises: 1cbc79e67ea7
Create Date: 2026-07-21 22:15:28.047017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdec1b1fd5cb'
down_revision: Union[str, None] = '1cbc79e67ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profile_snapshots',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
    "ix_career_profile_snapshots_profile_id",
    "career_profile_snapshots",
    ["profile_id"],
    )
    op.add_column('career_profiles', sa.Column('career_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('career_profiles', sa.Column('strongest_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('weakest_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('ai_maturity_score', sa.Float(), nullable=True))
    op.add_column('career_profiles', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('career_profiles', sa.Column('preferred_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('preferred_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('salary_expectations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('remote_preference', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('overall_growth_score', sa.Float(), nullable=True))
    op.add_column('career_profiles', sa.Column('readiness_score', sa.Float(), nullable=True))
    op.add_column('career_profiles', sa.Column('promotion_readiness', sa.Float(), nullable=True))
    op.add_column('career_profiles', sa.Column('ai_career_level', sa.String(), nullable=True))
    op.add_column('career_profiles', sa.Column('growth_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('learning_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('learning_roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('skill_intelligence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('career_profiles', sa.Column('career_gap_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('resume_versions', 'ats_score')
    op.drop_column('resume_versions', 'ats_details')
    op.drop_column('resume_versions', 'changes_made')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('changes_made', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resume_versions', sa.Column('ats_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('resume_versions', sa.Column('ats_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('career_profiles', 'career_gap_analysis')
    op.drop_column('career_profiles', 'skill_intelligence')
    op.drop_column('career_profiles', 'learning_roadmap')
    op.drop_column('career_profiles', 'learning_recommendations')
    op.drop_column('career_profiles', 'growth_summary')
    op.drop_column('career_profiles', 'ai_career_level')
    op.drop_column('career_profiles', 'promotion_readiness')
    op.drop_column('career_profiles', 'readiness_score')
    op.drop_column('career_profiles', 'overall_growth_score')
    op.drop_column('career_profiles', 'remote_preference')
    op.drop_column('career_profiles', 'salary_expectations')
    op.drop_column('career_profiles', 'preferred_locations')
    op.drop_column('career_profiles', 'preferred_roles')
    op.drop_column('career_profiles', 'preferred_industries')
    op.drop_column('career_profiles', 'confidence_score')
    op.drop_column('career_profiles', 'ai_maturity_score')
    op.drop_column('career_profiles', 'weakest_skills')
    op.drop_column('career_profiles', 'strongest_skills')
    op.drop_column('career_profiles', 'experience_level')
    op.drop_column('career_profiles', 'career_summary')
    op.drop_index(
    "ix_career_profile_snapshots_profile_id",
    table_name="career_profile_snapshots",
    )
    op.drop_table('career_profile_snapshots')
    # ### end Alembic commands ###
